services:
  - type: web
    name: kinnect
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCKER_BUILDKIT
        value: "1"
      - key: PORT
        value: "3000"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://kinnect-z7wf.onrender.com"
    healthCheckPath: /health
    healthCheckInterval: 30
    autoDeploy: true
